version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - echo Building React frontend for production...
      - npm run build
  post_build:
    commands:
      # Clear bucket contents to prevent sync conflicts
      - echo Cleaning S3 bucket...
      - aws s3 rm s3://$FRONTEND_S3_BUCKET --recursive
      
      # Upload build artifacts
      - echo Uploading static assets...
      - aws s3 sync dist/ s3://$FRONTEND_S3_BUCKET

      - echo "Checking available environment variables..."
      - env | grep VITE_ > env_debug.log
      - cat env_debug.log
      
      # Generate dynamic configuration file for runtime usage
      - |
        echo "{\"VITE_API_BASE_URL\": \"$VITE_API_URL\", \"VITE_AUTH_SERVER_URL\": \"$VITE_AUTH_SERVER_URL\", \"VITE_AUTH_CLIENT_ID\": \"$VITE_AUTH_CLIENT_ID\"}" > dist/config.json
      
      - echo "Generated config file content:"
      - cat dist/config.json
      
      # Upload the configuration file to S3
      - aws s3 cp dist/config.json s3://$FRONTEND_S3_BUCKET/config.json
      
      # Invalidate CloudFront cache
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"