version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - echo Building React frontend for production...
      - npm run build
  post_build:
    commands:
      # Clear bucket contents to prevent sync conflicts
      - echo Cleaning S3 bucket...
      - aws s3 rm s3://$FRONTEND_S3_BUCKET --recursive
      
      # Upload build artifacts
      - echo Uploading static assets...
      - aws s3 sync dist/ s3://$FRONTEND_S3_BUCKET
      
      # Invalidate CloudFront cache
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"